2023-11-22 00:28:57,960 INFO    StreamThr :17248 [internal.py:wandb_internal():86] W&B internal server running at pid: 17248, started at: 2023-11-22 00:28:57.959087
2023-11-22 00:28:57,961 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: status
2023-11-22 00:28:57,967 INFO    WriterThread:17248 [datastore.py:open_for_write():85] open: C:\Users\theho\git_AI_Application_Practice\07.Olympic\wandb\run-20231122_002857-5m4erl67\run-5m4erl67.wandb
2023-11-22 00:28:57,968 DEBUG   SenderThread:17248 [sender.py:send():380] send: header
2023-11-22 00:28:58,042 DEBUG   SenderThread:17248 [sender.py:send():380] send: run
2023-11-22 00:28:59,024 INFO    SenderThread:17248 [dir_watcher.py:__init__():211] watching files in: C:\Users\theho\git_AI_Application_Practice\07.Olympic\wandb\run-20231122_002857-5m4erl67\files
2023-11-22 00:28:59,024 INFO    SenderThread:17248 [sender.py:_start_run_threads():1124] run started: 5m4erl67 with start time 1700580537.960087
2023-11-22 00:28:59,042 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: check_version
2023-11-22 00:28:59,043 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: check_version
2023-11-22 00:28:59,639 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: run_start
2023-11-22 00:28:59,655 DEBUG   HandlerThread:17248 [system_info.py:__init__():32] System info init
2023-11-22 00:28:59,655 DEBUG   HandlerThread:17248 [system_info.py:__init__():47] System info init done
2023-11-22 00:28:59,655 INFO    HandlerThread:17248 [system_monitor.py:start():194] Starting system monitor
2023-11-22 00:28:59,657 INFO    SystemMonitor:17248 [system_monitor.py:_start():158] Starting system asset monitoring threads
2023-11-22 00:28:59,657 INFO    HandlerThread:17248 [system_monitor.py:probe():214] Collecting system info
2023-11-22 00:28:59,661 INFO    SystemMonitor:17248 [interfaces.py:start():190] Started cpu monitoring
2023-11-22 00:28:59,665 DEBUG   HandlerThread:17248 [system_info.py:probe():196] Probing system
2023-11-22 00:28:59,665 INFO    SystemMonitor:17248 [interfaces.py:start():190] Started disk monitoring
2023-11-22 00:28:59,674 INFO    SystemMonitor:17248 [interfaces.py:start():190] Started memory monitoring
2023-11-22 00:28:59,689 INFO    SystemMonitor:17248 [interfaces.py:start():190] Started network monitoring
2023-11-22 00:28:59,691 DEBUG   HandlerThread:17248 [system_info.py:_probe_git():181] Probing git
2023-11-22 00:28:59,832 DEBUG   HandlerThread:17248 [system_info.py:_probe_git():189] Probing git done
2023-11-22 00:28:59,832 DEBUG   HandlerThread:17248 [system_info.py:probe():244] Probing system done
2023-11-22 00:28:59,832 DEBUG   HandlerThread:17248 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.19045-SP0', 'python': '3.10.13', 'heartbeatAt': '2023-11-21T15:28:59.665994', 'startedAt': '2023-11-21T15:28:57.943002', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'C:\\Users\\theho\\git_AI_Application_Practice\\07.Olympic\\f_ppo_train.py', 'codePathLocal': 'f_ppo_train.py', 'codePath': '07.Olympic\\f_ppo_train.py', 'git': {'remote': 'https://github.com/dmlcksghd/AI_Application_Practice.git', 'commit': 'ae8cbaf3c58b5e9e3cb8d87a5adaff98542c6ed9'}, 'email': 'dmlcksghd', 'root': 'C:/Users/theho/git_AI_Application_Practice', 'host': 'DESKTOP-6GREP35', 'username': 'theho', 'executable': 'C:\\Users\\theho\\anaconda3\\envs\\AI_Lecture\\python.exe', 'cpu_count': 6, 'cpu_count_logical': 12, 'cpu_freq': {'current': 3400.0, 'min': 0.0, 'max': 3400.0}, 'cpu_freq_per_core': [{'current': 3400.0, 'min': 0.0, 'max': 3400.0}], 'disk': {'/': {'total': 464.688663482666, 'used': 237.4736442565918}}, 'memory': {'total': 15.948715209960938}}
2023-11-22 00:28:59,832 INFO    HandlerThread:17248 [system_monitor.py:probe():224] Finished collecting system info
2023-11-22 00:28:59,832 INFO    HandlerThread:17248 [system_monitor.py:probe():227] Publishing system info
2023-11-22 00:28:59,832 DEBUG   HandlerThread:17248 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2023-11-22 00:28:59,834 DEBUG   HandlerThread:17248 [system_info.py:_save_pip():68] Saving pip packages done
2023-11-22 00:28:59,834 DEBUG   HandlerThread:17248 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2023-11-22 00:29:00,042 INFO    Thread-16 :17248 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\theho\git_AI_Application_Practice\07.Olympic\wandb\run-20231122_002857-5m4erl67\files\conda-environment.yaml
2023-11-22 00:29:00,042 INFO    Thread-16 :17248 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\theho\git_AI_Application_Practice\07.Olympic\wandb\run-20231122_002857-5m4erl67\files\requirements.txt
2023-11-22 00:29:06,073 INFO    Thread-16 :17248 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\theho\git_AI_Application_Practice\07.Olympic\wandb\run-20231122_002857-5m4erl67\files\conda-environment.yaml
2023-11-22 00:29:06,131 DEBUG   HandlerThread:17248 [system_info.py:_save_conda():87] Saving conda packages done
2023-11-22 00:29:06,132 INFO    HandlerThread:17248 [system_monitor.py:probe():229] Finished publishing system info
2023-11-22 00:29:06,153 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: status_report
2023-11-22 00:29:06,154 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: keepalive
2023-11-22 00:29:06,154 DEBUG   SenderThread:17248 [sender.py:send():380] send: files
2023-11-22 00:29:06,154 INFO    SenderThread:17248 [sender.py:_save_file():1380] saving file wandb-metadata.json with policy now
2023-11-22 00:29:06,167 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: stop_status
2023-11-22 00:29:06,167 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: internal_messages
2023-11-22 00:29:06,168 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: stop_status
2023-11-22 00:29:07,050 DEBUG   SenderThread:17248 [sender.py:send():380] send: telemetry
2023-11-22 00:29:07,078 INFO    Thread-16 :17248 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\theho\git_AI_Application_Practice\07.Olympic\wandb\run-20231122_002857-5m4erl67\files\wandb-metadata.json
2023-11-22 00:29:07,521 INFO    wandb-upload_0:17248 [upload_job.py:push():131] Uploaded file C:\Users\theho\AppData\Local\Temp\tmpk_kxxlsewandb\04aqzo3p-wandb-metadata.json
2023-11-22 00:29:09,058 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: status_report
2023-11-22 00:29:14,084 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: status_report
2023-11-22 00:29:19,111 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: status_report
2023-11-22 00:29:21,165 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: stop_status
2023-11-22 00:29:21,165 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: stop_status
2023-11-22 00:29:21,171 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: internal_messages
2023-11-22 00:29:24,452 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: status_report
2023-11-22 00:29:29,483 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: status_report
2023-11-22 00:29:30,200 INFO    Thread-16 :17248 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\theho\git_AI_Application_Practice\07.Olympic\wandb\run-20231122_002857-5m4erl67\files\config.yaml
2023-11-22 00:29:34,776 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: status_report
2023-11-22 00:29:36,178 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: stop_status
2023-11-22 00:29:36,179 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: stop_status
2023-11-22 00:29:36,181 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: internal_messages
2023-11-22 00:29:40,463 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: status_report
2023-11-22 00:29:45,489 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: status_report
2023-11-22 00:29:50,515 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: status_report
2023-11-22 00:29:51,194 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: internal_messages
2023-11-22 00:29:51,198 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: stop_status
2023-11-22 00:29:51,198 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: stop_status
2023-11-22 00:29:56,456 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: status_report
2023-11-22 00:29:59,699 DEBUG   SystemMonitor:17248 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2023-11-22 00:29:59,700 DEBUG   SenderThread:17248 [sender.py:send():380] send: stats
2023-11-22 00:30:01,712 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: status_report
2023-11-22 00:30:06,194 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: internal_messages
2023-11-22 00:30:06,195 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: stop_status
2023-11-22 00:30:06,195 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: stop_status
2023-11-22 00:30:07,429 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: status_report
2023-11-22 00:30:12,456 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: status_report
2023-11-22 00:30:17,482 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: status_report
2023-11-22 00:30:21,191 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: internal_messages
2023-11-22 00:30:21,201 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: stop_status
2023-11-22 00:30:21,201 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: stop_status
2023-11-22 00:30:21,714 INFO    Thread-16 :17248 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\theho\git_AI_Application_Practice\07.Olympic\wandb\run-20231122_002857-5m4erl67\files\output.log
2023-11-22 00:30:22,493 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: status_report
2023-11-22 00:30:23,153 ERROR   FileStreamThread:17248 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/honguc/olympics-running/5m4erl67/file_stream
NoneType: None
2023-11-22 00:30:23,739 INFO    Thread-16 :17248 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\theho\git_AI_Application_Practice\07.Olympic\wandb\run-20231122_002857-5m4erl67\files\output.log
2023-11-22 00:30:27,522 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: status_report
2023-11-22 00:30:29,703 DEBUG   SenderThread:17248 [sender.py:send():380] send: stats
2023-11-22 00:30:32,719 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: status_report
2023-11-22 00:30:36,185 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: internal_messages
2023-11-22 00:30:36,186 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: stop_status
2023-11-22 00:30:36,192 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: stop_status
2023-11-22 00:30:38,436 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: status_report
2023-11-22 00:30:39,906 ERROR   FileStreamThread:17248 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/honguc/olympics-running/5m4erl67/file_stream
NoneType: None
2023-11-22 00:30:43,498 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: status_report
2023-11-22 00:30:48,526 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: status_report
2023-11-22 00:30:51,177 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: internal_messages
2023-11-22 00:30:51,182 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: stop_status
2023-11-22 00:30:51,183 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: stop_status
2023-11-22 00:30:51,731 DEBUG   SenderThread:17248 [sender.py:send():380] send: exit
2023-11-22 00:30:51,731 INFO    SenderThread:17248 [sender.py:send_exit():585] handling exit code: 255
2023-11-22 00:30:51,731 INFO    SenderThread:17248 [sender.py:send_exit():587] handling runtime: 112
2023-11-22 00:30:51,733 INFO    SenderThread:17248 [sender.py:_save_file():1380] saving file wandb-summary.json with policy end
2023-11-22 00:30:51,733 INFO    SenderThread:17248 [sender.py:send_exit():593] send defer
2023-11-22 00:30:51,734 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: defer
2023-11-22 00:30:51,734 INFO    HandlerThread:17248 [handler.py:handle_request_defer():172] handle defer: 0
2023-11-22 00:30:51,734 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: defer
2023-11-22 00:30:51,734 INFO    SenderThread:17248 [sender.py:send_request_defer():609] handle sender defer: 0
2023-11-22 00:30:51,734 INFO    SenderThread:17248 [sender.py:transition_state():613] send defer: 1
2023-11-22 00:30:51,735 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: defer
2023-11-22 00:30:51,735 INFO    HandlerThread:17248 [handler.py:handle_request_defer():172] handle defer: 1
2023-11-22 00:30:51,735 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: defer
2023-11-22 00:30:51,735 INFO    SenderThread:17248 [sender.py:send_request_defer():609] handle sender defer: 1
2023-11-22 00:30:51,735 INFO    SenderThread:17248 [sender.py:transition_state():613] send defer: 2
2023-11-22 00:30:51,735 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: defer
2023-11-22 00:30:51,735 INFO    HandlerThread:17248 [handler.py:handle_request_defer():172] handle defer: 2
2023-11-22 00:30:51,735 INFO    HandlerThread:17248 [system_monitor.py:finish():203] Stopping system monitor
2023-11-22 00:30:51,736 DEBUG   SystemMonitor:17248 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2023-11-22 00:30:51,736 INFO    HandlerThread:17248 [interfaces.py:finish():202] Joined cpu monitor
2023-11-22 00:30:51,736 DEBUG   SystemMonitor:17248 [system_monitor.py:_start():183] Publishing last batch of metrics
2023-11-22 00:30:51,736 INFO    HandlerThread:17248 [interfaces.py:finish():202] Joined disk monitor
2023-11-22 00:30:51,737 INFO    HandlerThread:17248 [interfaces.py:finish():202] Joined memory monitor
2023-11-22 00:30:51,737 INFO    HandlerThread:17248 [interfaces.py:finish():202] Joined network monitor
2023-11-22 00:30:51,738 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: defer
2023-11-22 00:30:51,738 INFO    SenderThread:17248 [sender.py:send_request_defer():609] handle sender defer: 2
2023-11-22 00:30:51,738 INFO    SenderThread:17248 [sender.py:transition_state():613] send defer: 3
2023-11-22 00:30:51,738 DEBUG   SenderThread:17248 [sender.py:send():380] send: stats
2023-11-22 00:30:51,738 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: defer
2023-11-22 00:30:51,739 INFO    HandlerThread:17248 [handler.py:handle_request_defer():172] handle defer: 3
2023-11-22 00:30:51,739 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: defer
2023-11-22 00:30:51,739 INFO    SenderThread:17248 [sender.py:send_request_defer():609] handle sender defer: 3
2023-11-22 00:30:51,739 INFO    SenderThread:17248 [sender.py:transition_state():613] send defer: 4
2023-11-22 00:30:51,739 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: defer
2023-11-22 00:30:51,739 INFO    HandlerThread:17248 [handler.py:handle_request_defer():172] handle defer: 4
2023-11-22 00:30:51,740 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: defer
2023-11-22 00:30:51,740 INFO    SenderThread:17248 [sender.py:send_request_defer():609] handle sender defer: 4
2023-11-22 00:30:51,740 INFO    SenderThread:17248 [sender.py:transition_state():613] send defer: 5
2023-11-22 00:30:51,740 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: defer
2023-11-22 00:30:51,740 INFO    HandlerThread:17248 [handler.py:handle_request_defer():172] handle defer: 5
2023-11-22 00:30:51,740 DEBUG   SenderThread:17248 [sender.py:send():380] send: summary
2023-11-22 00:30:51,741 INFO    SenderThread:17248 [sender.py:_save_file():1380] saving file wandb-summary.json with policy end
2023-11-22 00:30:51,742 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: defer
2023-11-22 00:30:51,742 INFO    SenderThread:17248 [sender.py:send_request_defer():609] handle sender defer: 5
2023-11-22 00:30:51,742 INFO    SenderThread:17248 [sender.py:transition_state():613] send defer: 6
2023-11-22 00:30:51,742 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: defer
2023-11-22 00:30:51,742 INFO    HandlerThread:17248 [handler.py:handle_request_defer():172] handle defer: 6
2023-11-22 00:30:51,743 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: defer
2023-11-22 00:30:51,743 INFO    SenderThread:17248 [sender.py:send_request_defer():609] handle sender defer: 6
2023-11-22 00:30:51,743 INFO    SenderThread:17248 [sender.py:transition_state():613] send defer: 7
2023-11-22 00:30:51,743 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: status_report
2023-11-22 00:30:51,743 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: defer
2023-11-22 00:30:51,743 INFO    HandlerThread:17248 [handler.py:handle_request_defer():172] handle defer: 7
2023-11-22 00:30:51,743 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: defer
2023-11-22 00:30:51,744 INFO    SenderThread:17248 [sender.py:send_request_defer():609] handle sender defer: 7
2023-11-22 00:30:51,926 ERROR   FileStreamThread:17248 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/honguc/olympics-running/5m4erl67/file_stream
NoneType: None
2023-11-22 00:30:52,146 INFO    Thread-16 :17248 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\theho\git_AI_Application_Practice\07.Olympic\wandb\run-20231122_002857-5m4erl67\files\wandb-summary.json
2023-11-22 00:30:52,745 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: poll_exit
2023-11-22 00:30:53,750 INFO    SenderThread:17248 [sender.py:transition_state():613] send defer: 8
2023-11-22 00:30:53,750 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: poll_exit
2023-11-22 00:30:53,750 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: defer
2023-11-22 00:30:53,751 INFO    HandlerThread:17248 [handler.py:handle_request_defer():172] handle defer: 8
2023-11-22 00:30:53,751 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: defer
2023-11-22 00:30:53,751 INFO    SenderThread:17248 [sender.py:send_request_defer():609] handle sender defer: 8
2023-11-22 00:30:53,751 INFO    SenderThread:17248 [job_builder.py:build():298] Attempting to build job artifact
2023-11-22 00:30:53,752 INFO    SenderThread:17248 [job_builder.py:_get_source_type():428] is repo sourced job
2023-11-22 00:30:53,755 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: poll_exit
2023-11-22 00:30:54,162 INFO    Thread-16 :17248 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\theho\git_AI_Application_Practice\07.Olympic\wandb\run-20231122_002857-5m4erl67\files\output.log
2023-11-22 00:30:54,352 INFO    SenderThread:17248 [job_builder.py:build():404] adding wandb-job metadata file
2023-11-22 00:30:54,367 INFO    SenderThread:17248 [sender.py:transition_state():613] send defer: 9
2023-11-22 00:30:54,368 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: poll_exit
2023-11-22 00:30:54,368 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: defer
2023-11-22 00:30:54,368 DEBUG   SenderThread:17248 [sender.py:send():380] send: artifact
2023-11-22 00:30:54,368 INFO    HandlerThread:17248 [handler.py:handle_request_defer():172] handle defer: 9
2023-11-22 00:30:54,761 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: poll_exit
2023-11-22 00:30:55,252 ERROR   SenderThread:17248 [internal_api.py:execute():370] 404 response executing GraphQL.
2023-11-22 00:30:55,252 ERROR   SenderThread:17248 [internal_api.py:execute():371] {"errors":[{"message":"failed to find run olympics-running/5m4erl67","path":["createArtifactManifest"]}],"data":{"createArtifactManifest":null}}
2023-11-22 00:30:55,254 ERROR   SenderThread:17248 [sender.py:send_artifact():1460] send_artifact: failed for artifact "job/job-https___github.com_dmlcksghd_AI_Application_Practice.git_07.Olympic_f_ppo_train.py": It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-11-22 00:30:55,255 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: defer
2023-11-22 00:30:55,255 INFO    SenderThread:17248 [sender.py:send_request_defer():609] handle sender defer: 9
2023-11-22 00:30:55,255 INFO    SenderThread:17248 [dir_watcher.py:finish():358] shutting down directory watcher
2023-11-22 00:30:56,171 INFO    SenderThread:17248 [dir_watcher.py:finish():388] scan: C:\Users\theho\git_AI_Application_Practice\07.Olympic\wandb\run-20231122_002857-5m4erl67\files
2023-11-22 00:30:56,171 INFO    SenderThread:17248 [dir_watcher.py:finish():402] scan save: C:\Users\theho\git_AI_Application_Practice\07.Olympic\wandb\run-20231122_002857-5m4erl67\files\conda-environment.yaml conda-environment.yaml
2023-11-22 00:30:56,172 INFO    SenderThread:17248 [dir_watcher.py:finish():402] scan save: C:\Users\theho\git_AI_Application_Practice\07.Olympic\wandb\run-20231122_002857-5m4erl67\files\config.yaml config.yaml
2023-11-22 00:30:56,174 INFO    SenderThread:17248 [dir_watcher.py:finish():402] scan save: C:\Users\theho\git_AI_Application_Practice\07.Olympic\wandb\run-20231122_002857-5m4erl67\files\output.log output.log
2023-11-22 00:30:56,177 INFO    SenderThread:17248 [dir_watcher.py:finish():402] scan save: C:\Users\theho\git_AI_Application_Practice\07.Olympic\wandb\run-20231122_002857-5m4erl67\files\requirements.txt requirements.txt
2023-11-22 00:30:56,181 INFO    SenderThread:17248 [dir_watcher.py:finish():402] scan save: C:\Users\theho\git_AI_Application_Practice\07.Olympic\wandb\run-20231122_002857-5m4erl67\files\wandb-metadata.json wandb-metadata.json
2023-11-22 00:30:56,181 INFO    SenderThread:17248 [dir_watcher.py:finish():402] scan save: C:\Users\theho\git_AI_Application_Practice\07.Olympic\wandb\run-20231122_002857-5m4erl67\files\wandb-summary.json wandb-summary.json
2023-11-22 00:30:56,184 INFO    SenderThread:17248 [sender.py:transition_state():613] send defer: 10
2023-11-22 00:30:56,185 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: poll_exit
2023-11-22 00:30:56,185 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: defer
2023-11-22 00:30:56,187 INFO    HandlerThread:17248 [handler.py:handle_request_defer():172] handle defer: 10
2023-11-22 00:30:56,188 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: defer
2023-11-22 00:30:56,188 INFO    SenderThread:17248 [sender.py:send_request_defer():609] handle sender defer: 10
2023-11-22 00:30:56,188 INFO    SenderThread:17248 [file_pusher.py:finish():175] shutting down file pusher
2023-11-22 00:30:56,374 ERROR   wandb-upload_1:17248 [internal_api.py:execute():370] 404 response executing GraphQL.
2023-11-22 00:30:56,374 ERROR   wandb-upload_1:17248 [internal_api.py:execute():371] {"errors":[{"message":"run olympics-running/5m4erl67 not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2023-11-22 00:30:56,374 ERROR   Thread-15 (_thread_body):17248 [step_upload.py:_handle_event():200] Failed to upload file: C:\Users\theho\git_AI_Application_Practice\07.Olympic\wandb\run-20231122_002857-5m4erl67\files\config.yaml
Traceback (most recent call last):
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\internal\internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\filesync\step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\filesync\step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\filesync\upload_job.py", line 57, in run
    self.push()
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\filesync\upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\apis\normalize.py", line 73, in wrapper
    raise err
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2176, in upload_urls
    query_result = self.gql(
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\internal\internal_api.py", line 338, in gql
    ret = self._retry_gql(
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\lib\retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\util.py", line 907, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-11-22 00:30:56,376 ERROR   wandb-upload_0:17248 [internal_api.py:execute():370] 404 response executing GraphQL.
2023-11-22 00:30:56,384 ERROR   wandb-upload_0:17248 [internal_api.py:execute():371] {"errors":[{"message":"run olympics-running/5m4erl67 not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2023-11-22 00:30:56,385 ERROR   Thread-15 (_thread_body):17248 [step_upload.py:_handle_event():200] Failed to upload file: C:\Users\theho\git_AI_Application_Practice\07.Olympic\wandb\run-20231122_002857-5m4erl67\files\conda-environment.yaml
Traceback (most recent call last):
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\internal\internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\filesync\step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\filesync\step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\filesync\upload_job.py", line 57, in run
    self.push()
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\filesync\upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\apis\normalize.py", line 73, in wrapper
    raise err
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2176, in upload_urls
    query_result = self.gql(
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\internal\internal_api.py", line 338, in gql
    ret = self._retry_gql(
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\lib\retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\util.py", line 907, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-11-22 00:30:57,180 ERROR   wandb-upload_4:17248 [internal_api.py:execute():370] 404 response executing GraphQL.
2023-11-22 00:30:57,180 ERROR   wandb-upload_4:17248 [internal_api.py:execute():371] {"errors":[{"message":"run olympics-running/5m4erl67 not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2023-11-22 00:30:57,181 ERROR   wandb-upload_2:17248 [internal_api.py:execute():370] 404 response executing GraphQL.
2023-11-22 00:30:57,181 ERROR   Thread-15 (_thread_body):17248 [step_upload.py:_handle_event():200] Failed to upload file: C:\Users\theho\git_AI_Application_Practice\07.Olympic\wandb\run-20231122_002857-5m4erl67\files\wandb-summary.json
Traceback (most recent call last):
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\internal\internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\filesync\step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\filesync\step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\filesync\upload_job.py", line 57, in run
    self.push()
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\filesync\upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\apis\normalize.py", line 73, in wrapper
    raise err
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2176, in upload_urls
    query_result = self.gql(
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\internal\internal_api.py", line 338, in gql
    ret = self._retry_gql(
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\lib\retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\util.py", line 907, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-11-22 00:30:57,182 ERROR   wandb-upload_2:17248 [internal_api.py:execute():371] {"errors":[{"message":"run olympics-running/5m4erl67 not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2023-11-22 00:30:57,183 ERROR   Thread-15 (_thread_body):17248 [step_upload.py:_handle_event():200] Failed to upload file: C:\Users\theho\git_AI_Application_Practice\07.Olympic\wandb\run-20231122_002857-5m4erl67\files\output.log
Traceback (most recent call last):
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\internal\internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\filesync\step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\filesync\step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\filesync\upload_job.py", line 57, in run
    self.push()
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\filesync\upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\apis\normalize.py", line 73, in wrapper
    raise err
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2176, in upload_urls
    query_result = self.gql(
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\internal\internal_api.py", line 338, in gql
    ret = self._retry_gql(
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\lib\retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\util.py", line 907, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-11-22 00:30:57,194 ERROR   wandb-upload_3:17248 [internal_api.py:execute():370] 404 response executing GraphQL.
2023-11-22 00:30:57,194 ERROR   wandb-upload_3:17248 [internal_api.py:execute():371] {"errors":[{"message":"run olympics-running/5m4erl67 not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2023-11-22 00:30:57,194 ERROR   Thread-15 (_thread_body):17248 [step_upload.py:_handle_event():200] Failed to upload file: C:\Users\theho\git_AI_Application_Practice\07.Olympic\wandb\run-20231122_002857-5m4erl67\files\requirements.txt
Traceback (most recent call last):
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\internal\internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\filesync\step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\filesync\step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\filesync\upload_job.py", line 57, in run
    self.push()
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\filesync\upload_job.py", line 106, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\apis\normalize.py", line 73, in wrapper
    raise err
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2176, in upload_urls
    query_result = self.gql(
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\internal\internal_api.py", line 338, in gql
    ret = self._retry_gql(
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\sdk\lib\retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "C:\Users\theho\anaconda3\envs\AI_Lecture\lib\site-packages\wandb\util.py", line 907, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-11-22 00:30:57,402 INFO    Thread-15 (_thread_body):17248 [sender.py:transition_state():613] send defer: 11
2023-11-22 00:30:57,402 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: defer
2023-11-22 00:30:57,402 INFO    HandlerThread:17248 [handler.py:handle_request_defer():172] handle defer: 11
2023-11-22 00:30:57,403 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: defer
2023-11-22 00:30:57,403 INFO    SenderThread:17248 [sender.py:send_request_defer():609] handle sender defer: 11
2023-11-22 00:30:57,403 INFO    SenderThread:17248 [file_pusher.py:join():181] waiting for file pusher
2023-11-22 00:30:57,403 INFO    SenderThread:17248 [sender.py:transition_state():613] send defer: 12
2023-11-22 00:30:57,403 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: defer
2023-11-22 00:30:57,403 INFO    HandlerThread:17248 [handler.py:handle_request_defer():172] handle defer: 12
2023-11-22 00:30:57,403 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: defer
2023-11-22 00:30:57,404 INFO    SenderThread:17248 [sender.py:send_request_defer():609] handle sender defer: 12
2023-11-22 00:30:57,404 INFO    SenderThread:17248 [file_stream.py:finish():595] file stream finish called
2023-11-22 00:30:57,600 ERROR   FileStreamThread:17248 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/honguc/olympics-running/5m4erl67/file_stream
NoneType: None
2023-11-22 00:30:57,786 INFO    SenderThread:17248 [file_stream.py:finish():599] file stream finish is done
2023-11-22 00:30:57,787 INFO    SenderThread:17248 [sender.py:transition_state():613] send defer: 13
2023-11-22 00:30:57,787 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: defer
2023-11-22 00:30:57,787 INFO    HandlerThread:17248 [handler.py:handle_request_defer():172] handle defer: 13
2023-11-22 00:30:57,787 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: defer
2023-11-22 00:30:57,787 INFO    SenderThread:17248 [sender.py:send_request_defer():609] handle sender defer: 13
2023-11-22 00:30:57,787 INFO    SenderThread:17248 [sender.py:transition_state():613] send defer: 14
2023-11-22 00:30:57,788 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: defer
2023-11-22 00:30:57,788 DEBUG   SenderThread:17248 [sender.py:send():380] send: final
2023-11-22 00:30:57,788 INFO    HandlerThread:17248 [handler.py:handle_request_defer():172] handle defer: 14
2023-11-22 00:30:57,788 DEBUG   SenderThread:17248 [sender.py:send():380] send: footer
2023-11-22 00:30:57,788 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: defer
2023-11-22 00:30:57,788 INFO    SenderThread:17248 [sender.py:send_request_defer():609] handle sender defer: 14
2023-11-22 00:30:57,789 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: poll_exit
2023-11-22 00:30:57,789 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: server_info
2023-11-22 00:30:57,789 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: get_summary
2023-11-22 00:30:57,789 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: poll_exit
2023-11-22 00:30:57,790 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: sampled_history
2023-11-22 00:30:57,790 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: server_info
2023-11-22 00:30:57,790 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: internal_messages
2023-11-22 00:30:57,792 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: job_info
2023-11-22 00:30:57,991 DEBUG   SenderThread:17248 [sender.py:send_request():407] send_request: job_info
2023-11-22 00:30:57,992 INFO    MainThread:17248 [wandb_run.py:_footer_history_summary_info():3760] rendering history
2023-11-22 00:30:57,992 INFO    MainThread:17248 [wandb_run.py:_footer_history_summary_info():3792] rendering summary
2023-11-22 00:30:57,992 INFO    MainThread:17248 [wandb_run.py:_footer_sync_info():3719] logging synced files
2023-11-22 00:30:57,992 DEBUG   HandlerThread:17248 [handler.py:handle_request():146] handle_request: shutdown
2023-11-22 00:30:57,992 INFO    HandlerThread:17248 [handler.py:finish():866] shutting down handler
2023-11-22 00:30:58,801 INFO    WriterThread:17248 [datastore.py:close():294] close: C:\Users\theho\git_AI_Application_Practice\07.Olympic\wandb\run-20231122_002857-5m4erl67\run-5m4erl67.wandb
2023-11-22 00:30:58,997 INFO    SenderThread:17248 [sender.py:finish():1536] shutting down sender
2023-11-22 00:30:58,997 INFO    SenderThread:17248 [file_pusher.py:finish():175] shutting down file pusher
2023-11-22 00:30:58,997 INFO    SenderThread:17248 [file_pusher.py:join():181] waiting for file pusher
